// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.IT.GRM.ServiceClient;
using Microsoft.IT.GRM.ServiceClient.Models;
using Microsoft.Rest;

namespace Microsoft.IT.GRM.ServiceClient
{
    public static partial class CalendarExtensions
    {
        /// <param name='operations'>
        /// Reference to the Microsoft.IT.GRM.ServiceClient.ICalendar.
        /// </param>
        /// <param name='calendarRequest'>
        /// Required.
        /// </param>
        /// <param name='trackingId'>
        /// Required. TrackingId (Guid) for Tracing. This will be present in
        /// Response Headers as well.
        /// </param>
        public static string Get(this ICalendar operations, GetCalendarRequest calendarRequest, string trackingId)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICalendar)s).GetAsync(calendarRequest, trackingId);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Microsoft.IT.GRM.ServiceClient.ICalendar.
        /// </param>
        /// <param name='calendarRequest'>
        /// Required.
        /// </param>
        /// <param name='trackingId'>
        /// Required. TrackingId (Guid) for Tracing. This will be present in
        /// Response Headers as well.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<string> GetAsync(this ICalendar operations, GetCalendarRequest calendarRequest, string trackingId, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<string> result = await operations.GetWithOperationResponseAsync(calendarRequest, trackingId, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Microsoft.IT.GRM.ServiceClient.ICalendar.
        /// </param>
        /// <param name='calendarRequest'>
        /// Required.
        /// </param>
        /// <param name='trackingId'>
        /// Required. TrackingId (Guid) for Tracing. This will be present in
        /// Response Headers as well.
        /// </param>
        public static string Post(this ICalendar operations, CreateCalendarRequest calendarRequest, string trackingId)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICalendar)s).PostAsync(calendarRequest, trackingId);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Microsoft.IT.GRM.ServiceClient.ICalendar.
        /// </param>
        /// <param name='calendarRequest'>
        /// Required.
        /// </param>
        /// <param name='trackingId'>
        /// Required. TrackingId (Guid) for Tracing. This will be present in
        /// Response Headers as well.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<string> PostAsync(this ICalendar operations, CreateCalendarRequest calendarRequest, string trackingId, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<string> result = await operations.PostWithOperationResponseAsync(calendarRequest, trackingId, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
