// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Microsoft.IT.GRM.ServiceClient;
using Microsoft.Rest;

namespace Microsoft.IT.GRM.ServiceClient
{
    public partial interface IServiceClient : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri
        {
            get; set; 
        }
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        ServiceClientCredentials Credentials
        {
            get; set; 
        }
        
        ICalendar Calendar
        {
            get; 
        }
        
        IDomainData DomainData
        {
            get; 
        }
        
        IRequest Request
        {
            get; 
        }
        
        IUserFilters UserFilters
        {
            get; 
        }
    }
}
