// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.IT.GRM.ServiceClient.Models;
using Microsoft.Rest;

namespace Microsoft.IT.GRM.ServiceClient
{
    public partial interface IUserFilters
    {
        /// <param name='deleteFilter'>
        /// Required.
        /// </param>
        /// <param name='trackingId'>
        /// Required. TrackingId (Guid) for Tracing. This will be present in
        /// Response Headers as well.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> DeleteFilterWithOperationResponseAsync(DeleteUserFilterRequest deleteFilter, string trackingId, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='defaultGetFilter'>
        /// Required.
        /// </param>
        /// <param name='trackingId'>
        /// Required. TrackingId (Guid) for Tracing. This will be present in
        /// Response Headers as well.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetDefaultFilterWithOperationResponseAsync(GetDefaultFilterRequest defaultGetFilter, string trackingId, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='saveFilter'>
        /// Required.
        /// </param>
        /// <param name='trackingId'>
        /// Required. TrackingId (Guid) for Tracing. This will be present in
        /// Response Headers as well.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<SavedFiltersDictionary>> SaveFilterWithOperationResponseAsync(SaveUserFilterRequest saveFilter, string trackingId, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='defaultFilter'>
        /// Required.
        /// </param>
        /// <param name='trackingId'>
        /// Required. TrackingId (Guid) for Tracing. This will be present in
        /// Response Headers as well.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> SetFilterAsDefaultWithOperationResponseAsync(DefaultUserFilterRequest defaultFilter, string trackingId, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='viewFilters'>
        /// Required.
        /// </param>
        /// <param name='trackingId'>
        /// Required. TrackingId (Guid) for Tracing. This will be present in
        /// Response Headers as well.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<SavedUserFilter>> ViewFiltersWithOperationResponseAsync(ViewUserFilterRequest viewFilters, string trackingId, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
