// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using Microsoft.IT.GRM.ServiceClient;
using Microsoft.Rest;

namespace Microsoft.IT.GRM.ServiceClient
{
    public partial class ServieClient : ServiceClient<ServieClient>, IServiceClient
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private ICalendar _calendar;
        
        public virtual ICalendar Calendar
        {
            get { return this._calendar; }
        }
        
        private IDomainData _domainData;
        
        public virtual IDomainData DomainData
        {
            get { return this._domainData; }
        }
        
        private IRequest _request;
        
        public virtual IRequest Request
        {
            get { return this._request; }
        }
        
        private IUserFilters _userFilters;
        
        public virtual IUserFilters UserFilters
        {
            get { return this._userFilters; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Unknowntype class.
        /// </summary>
        public ServieClient()
            : base()
        {
            this._calendar = new Calendar(this);
            this._domainData = new DomainData(this);
            this._request = new Request(this);
            this._userFilters = new UserFilters(this);
            this._baseUri = new Uri("http://localhost:2879");
        }
        
        /// <summary>
        /// Initializes a new instance of the Unknowntype class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public ServieClient(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._calendar = new Calendar(this);
            this._domainData = new DomainData(this);
            this._request = new Request(this);
            this._userFilters = new UserFilters(this);
            this._baseUri = new Uri("http://localhost:2879");
        }
        
        /// <summary>
        /// Initializes a new instance of the Unknowntype class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public ServieClient(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._calendar = new Calendar(this);
            this._domainData = new DomainData(this);
            this._request = new Request(this);
            this._userFilters = new UserFilters(this);
            this._baseUri = new Uri("http://localhost:2879");
        }
        
        /// <summary>
        /// Initializes a new instance of the Unknowntype class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public ServieClient(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the Unknowntype class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public ServieClient(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the Unknowntype class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public ServieClient(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
