// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ConsoleApplication1
{
    public static partial class StringDictionary
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IDictionary<string, string> DeserializeJson(JToken inputObject)
        {
            IDictionary<string, string> deserializedObject = new Dictionary<string, string>();
            foreach (JProperty property in inputObject)
            {
                deserializedObject.Add(((string)property.Name), ((string)property.Value));
            }
            return deserializedObject;
        }
    }
}
