// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ConsoleApplication1;
using Microsoft.Rest;

namespace ConsoleApplication1
{
    public static partial class ValuesExtensions
    {
        /// <param name='operations'>
        /// Reference to the ConsoleApplication1.IValues.
        /// </param>
        public static IDictionary<string, string> Get(this IValues operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IValues)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ConsoleApplication1.IValues.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IDictionary<string, string>> GetAsync(this IValues operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IDictionary<string, string>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
