// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class AcceptRequestRequest
    {
        private string _alias;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Alias
        {
            get { return this._alias; }
            set { this._alias = value; }
        }
        
        private IList<int?> _requestIds;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<int?> RequestIds
        {
            get { return this._requestIds; }
            set { this._requestIds = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the AcceptRequestRequest class.
        /// </summary>
        public AcceptRequestRequest()
        {
            this.RequestIds = new LazyList<int?>();
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type AcceptRequestRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Alias != null)
            {
                outputObject["Alias"] = this.Alias;
            }
            JArray requestIdsSequence = null;
            if (this.RequestIds != null)
            {
                if (this.RequestIds is ILazyCollection<int> == false || ((ILazyCollection<int>)this.RequestIds).IsInitialized)
                {
                    requestIdsSequence = new JArray();
                    outputObject["RequestIds"] = requestIdsSequence;
                    foreach (int? requestIdsItem in this.RequestIds)
                    {
                        if (requestIdsItem != null)
                        {
                            requestIdsSequence.Add(requestIdsItem.Value);
                        }
                    }
                }
            }
            return outputObject;
        }
    }
}
