// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.IT.GRM.ServiceClient.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class CreateCalendarRequest
    {
        private string _bookingType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string BookingType
        {
            get { return this._bookingType; }
            set { this._bookingType = value; }
        }
        
        private long _requestId;
        
        /// <summary>
        /// Required.
        /// </summary>
        public long RequestId
        {
            get { return this._requestId; }
            set { this._requestId = value; }
        }
        
        private IList<Schedule> _schedules;
        
        /// <summary>
        /// Required.
        /// </summary>
        public IList<Schedule> Schedules
        {
            get { return this._schedules; }
            set { this._schedules = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the CreateCalendarRequest class.
        /// </summary>
        public CreateCalendarRequest()
        {
            this.Schedules = new LazyList<Schedule>();
        }
        
        /// <summary>
        /// Initializes a new instance of the CreateCalendarRequest class with
        /// required arguments.
        /// </summary>
        public CreateCalendarRequest(long requestId, IList<Schedule> schedules)
            : this()
        {
            if (schedules == null)
            {
                throw new ArgumentNullException("schedules");
            }
            this.RequestId = requestId;
            this.Schedules = schedules;
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type CreateCalendarRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Schedules is ILazyCollection<Schedule> && ((ILazyCollection<Schedule>)this.Schedules).IsInitialized == false || this.Schedules == null)
            {
                throw new ArgumentNullException("Schedules");
            }
            if (this.BookingType != null)
            {
                outputObject["BookingType"] = this.BookingType;
            }
            outputObject["RequestId"] = this.RequestId;
            JArray schedulesSequence = null;
            if (this.Schedules != null)
            {
                if (this.Schedules is ILazyCollection<Schedule> == false || ((ILazyCollection<Schedule>)this.Schedules).IsInitialized)
                {
                    schedulesSequence = new JArray();
                    outputObject["Schedules"] = schedulesSequence;
                    foreach (Schedule schedulesItem in this.Schedules)
                    {
                        if (schedulesItem != null)
                        {
                            schedulesSequence.Add(schedulesItem.SerializeJson(null));
                        }
                    }
                }
            }
            return outputObject;
        }
    }
}
