// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class DefaultUserFilterRequest
    {
        private string _filterName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string FilterName
        {
            get { return this._filterName; }
            set { this._filterName = value; }
        }
        
        private bool? _isDefault;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsDefault
        {
            get { return this._isDefault; }
            set { this._isDefault = value; }
        }
        
        private string _requestStatus;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RequestStatus
        {
            get { return this._requestStatus; }
            set { this._requestStatus = value; }
        }
        
        private string _type;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Type
        {
            get { return this._type; }
            set { this._type = value; }
        }
        
        private string _userAlias;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string UserAlias
        {
            get { return this._userAlias; }
            set { this._userAlias = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the DefaultUserFilterRequest class.
        /// </summary>
        public DefaultUserFilterRequest()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type DefaultUserFilterRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.FilterName != null)
            {
                outputObject["FilterName"] = this.FilterName;
            }
            if (this.IsDefault != null)
            {
                outputObject["IsDefault"] = this.IsDefault.Value;
            }
            if (this.RequestStatus != null)
            {
                outputObject["RequestStatus"] = this.RequestStatus;
            }
            if (this.Type != null)
            {
                outputObject["Type"] = this.Type;
            }
            if (this.UserAlias != null)
            {
                outputObject["UserAlias"] = this.UserAlias;
            }
            return outputObject;
        }
    }
}
