// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class DefaultFilterKey
    {
        private string _requestStatus;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RequestStatus
        {
            get { return this._requestStatus; }
            set { this._requestStatus = value; }
        }
        
        private string _userAlias;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string UserAlias
        {
            get { return this._userAlias; }
            set { this._userAlias = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the DefaultFilterKey class.
        /// </summary>
        public DefaultFilterKey()
        {
        }
    }
}
