// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class FilterList
    {
        private IList<string> _filterlists;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<string> Filterlists
        {
            get { return this._filterlists; }
            set { this._filterlists = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the FilterList class.
        /// </summary>
        public FilterList()
        {
            this.Filterlists = new LazyList<string>();
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type FilterList
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            JArray filterlistsSequence = null;
            if (this.Filterlists != null)
            {
                if (this.Filterlists is ILazyCollection<string> == false || ((ILazyCollection<string>)this.Filterlists).IsInitialized)
                {
                    filterlistsSequence = new JArray();
                    outputObject["Filterlists"] = filterlistsSequence;
                    foreach (string filterlistsItem in this.Filterlists)
                    {
                        if (filterlistsItem != null)
                        {
                            filterlistsSequence.Add(filterlistsItem);
                        }
                    }
                }
            }
            return outputObject;
        }
    }
}
