// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class Geography
    {
        private int? _areaID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? AreaID
        {
            get { return this._areaID; }
            set { this._areaID = value; }
        }
        
        private string _areaName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AreaName
        {
            get { return this._areaName; }
            set { this._areaName = value; }
        }
        
        private int? _bigAreaID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? BigAreaID
        {
            get { return this._bigAreaID; }
            set { this._bigAreaID = value; }
        }
        
        private string _bigAreaName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string BigAreaName
        {
            get { return this._bigAreaName; }
            set { this._bigAreaName = value; }
        }
        
        private int? _countryId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? CountryId
        {
            get { return this._countryId; }
            set { this._countryId = value; }
        }
        
        private string _countryName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string CountryName
        {
            get { return this._countryName; }
            set { this._countryName = value; }
        }
        
        private int? _regionCountryID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? RegionCountryID
        {
            get { return this._regionCountryID; }
            set { this._regionCountryID = value; }
        }
        
        private string _regionCountryName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RegionCountryName
        {
            get { return this._regionCountryName; }
            set { this._regionCountryName = value; }
        }
        
        private int? _regionID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? RegionID
        {
            get { return this._regionID; }
            set { this._regionID = value; }
        }
        
        private string _regionName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RegionName
        {
            get { return this._regionName; }
            set { this._regionName = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Geography class.
        /// </summary>
        public Geography()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Geography
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.AreaID != null)
            {
                outputObject["AreaID"] = this.AreaID.Value;
            }
            if (this.AreaName != null)
            {
                outputObject["AreaName"] = this.AreaName;
            }
            if (this.BigAreaID != null)
            {
                outputObject["BigAreaID"] = this.BigAreaID.Value;
            }
            if (this.BigAreaName != null)
            {
                outputObject["BigAreaName"] = this.BigAreaName;
            }
            if (this.CountryId != null)
            {
                outputObject["CountryId"] = this.CountryId.Value;
            }
            if (this.CountryName != null)
            {
                outputObject["CountryName"] = this.CountryName;
            }
            if (this.RegionCountryID != null)
            {
                outputObject["RegionCountryID"] = this.RegionCountryID.Value;
            }
            if (this.RegionCountryName != null)
            {
                outputObject["RegionCountryName"] = this.RegionCountryName;
            }
            if (this.RegionID != null)
            {
                outputObject["RegionID"] = this.RegionID.Value;
            }
            if (this.RegionName != null)
            {
                outputObject["RegionName"] = this.RegionName;
            }
            return outputObject;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken areaIDValue = inputObject["AreaID"];
                if (areaIDValue != null && areaIDValue.Type != JTokenType.Null)
                {
                    this.AreaID = ((int)areaIDValue);
                }
                JToken areaNameValue = inputObject["AreaName"];
                if (areaNameValue != null && areaNameValue.Type != JTokenType.Null)
                {
                    this.AreaName = ((string)areaNameValue);
                }
                JToken bigAreaIDValue = inputObject["BigAreaID"];
                if (bigAreaIDValue != null && bigAreaIDValue.Type != JTokenType.Null)
                {
                    this.BigAreaID = ((int)bigAreaIDValue);
                }
                JToken bigAreaNameValue = inputObject["BigAreaName"];
                if (bigAreaNameValue != null && bigAreaNameValue.Type != JTokenType.Null)
                {
                    this.BigAreaName = ((string)bigAreaNameValue);
                }
                JToken countryIdValue = inputObject["CountryId"];
                if (countryIdValue != null && countryIdValue.Type != JTokenType.Null)
                {
                    this.CountryId = ((int)countryIdValue);
                }
                JToken countryNameValue = inputObject["CountryName"];
                if (countryNameValue != null && countryNameValue.Type != JTokenType.Null)
                {
                    this.CountryName = ((string)countryNameValue);
                }
                JToken regionCountryIDValue = inputObject["RegionCountryID"];
                if (regionCountryIDValue != null && regionCountryIDValue.Type != JTokenType.Null)
                {
                    this.RegionCountryID = ((int)regionCountryIDValue);
                }
                JToken regionCountryNameValue = inputObject["RegionCountryName"];
                if (regionCountryNameValue != null && regionCountryNameValue.Type != JTokenType.Null)
                {
                    this.RegionCountryName = ((string)regionCountryNameValue);
                }
                JToken regionIDValue = inputObject["RegionID"];
                if (regionIDValue != null && regionIDValue.Type != JTokenType.Null)
                {
                    this.RegionID = ((int)regionIDValue);
                }
                JToken regionNameValue = inputObject["RegionName"];
                if (regionNameValue != null && regionNameValue.Type != JTokenType.Null)
                {
                    this.RegionName = ((string)regionNameValue);
                }
            }
        }
    }
}
