// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class GetCalendarRequest
    {
        private string _calendarMode;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string CalendarMode
        {
            get { return this._calendarMode; }
            set { this._calendarMode = value; }
        }
        
        private DateTimeOffset _endDate;
        
        /// <summary>
        /// Required.
        /// </summary>
        public DateTimeOffset EndDate
        {
            get { return this._endDate; }
            set { this._endDate = value; }
        }
        
        private string _resourceId;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string ResourceId
        {
            get { return this._resourceId; }
            set { this._resourceId = value; }
        }
        
        private DateTimeOffset _startDate;
        
        /// <summary>
        /// Required.
        /// </summary>
        public DateTimeOffset StartDate
        {
            get { return this._startDate; }
            set { this._startDate = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the GetCalendarRequest class.
        /// </summary>
        public GetCalendarRequest()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type GetCalendarRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.CalendarMode == null)
            {
                throw new ArgumentNullException("CalendarMode");
            }
            if (this.ResourceId == null)
            {
                throw new ArgumentNullException("ResourceId");
            }
            if (this.CalendarMode != null)
            {
                outputObject["CalendarMode"] = this.CalendarMode;
            }
            outputObject["EndDate"] = this.EndDate;
            if (this.ResourceId != null)
            {
                outputObject["ResourceId"] = this.ResourceId;
            }
            outputObject["StartDate"] = this.StartDate;
            return outputObject;
        }
    }
}
