// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Microsoft.IT.GRM.ServiceClient.Models;
using Newtonsoft.Json.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class GetRequestsRequest
    {
        private SearchFilters _searchFilterValues;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public SearchFilters SearchFilterValues
        {
            get { return this._searchFilterValues; }
            set { this._searchFilterValues = value; }
        }
        
        private string _status;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Status
        {
            get { return this._status; }
            set { this._status = value; }
        }
        
        private string _userAlias;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string UserAlias
        {
            get { return this._userAlias; }
            set { this._userAlias = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the GetRequestsRequest class.
        /// </summary>
        public GetRequestsRequest()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type GetRequestsRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.SearchFilterValues != null)
            {
                outputObject["SearchFilterValues"] = this.SearchFilterValues.SerializeJson(null);
            }
            if (this.Status != null)
            {
                outputObject["Status"] = this.Status;
            }
            if (this.UserAlias != null)
            {
                outputObject["UserAlias"] = this.UserAlias;
            }
            return outputObject;
        }
    }
}
