// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Microsoft.IT.GRM.ServiceClient.Models;
using Newtonsoft.Json.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class SaveUserFilterRequest
    {
        private UserPreferenceSavedUserFilter _saveFilter;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public UserPreferenceSavedUserFilter SaveFilter
        {
            get { return this._saveFilter; }
            set { this._saveFilter = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SaveUserFilterRequest class.
        /// </summary>
        public SaveUserFilterRequest()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type SaveUserFilterRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.SaveFilter != null)
            {
                outputObject["SaveFilter"] = this.SaveFilter.SerializeJson(null);
            }
            return outputObject;
        }
    }
}
