// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.IT.GRM.ServiceClient.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class SavedFiltersDictionary
    {
        private IDictionary<string, string> _key;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IDictionary<string, string> Key
        {
            get { return this._key; }
            set { this._key = value; }
        }
        
        private SearchFilter _value;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public SearchFilter Value
        {
            get { return this._value; }
            set { this._value = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SavedFiltersDictionary class.
        /// </summary>
        public SavedFiltersDictionary()
        {
            this.Key = new LazyDictionary<string, string>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken objectDictionary = ((JToken)inputObject["Object"]);
                if (objectDictionary != null && objectDictionary.Type != JTokenType.Null)
                {
                    foreach (JProperty property in objectDictionary)
                    {
                        this.Key.Add(((string)property.Name), property.Value.ToString(Newtonsoft.Json.Formatting.Indented));
                    }
                }
                JToken valueValue = inputObject["Value"];
                if (valueValue != null && valueValue.Type != JTokenType.Null)
                {
                    SearchFilter searchFilter = new SearchFilter();
                    searchFilter.DeserializeJson(valueValue);
                    this.Value = searchFilter;
                }
            }
        }
    }
}
