// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.IT.GRM.ServiceClient.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class SavedUserFilter
    {
        private IDictionary<string, string> _defaultSearchFilterDictionary;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IDictionary<string, string> DefaultSearchFilterDictionary
        {
            get { return this._defaultSearchFilterDictionary; }
            set { this._defaultSearchFilterDictionary = value; }
        }
        
        private IDictionary<string, SearchFilter> _savedFiltersDictionary;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IDictionary<string, SearchFilter> SavedFiltersDictionary
        {
            get { return this._savedFiltersDictionary; }
            set { this._savedFiltersDictionary = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SavedUserFilter class.
        /// </summary>
        public SavedUserFilter()
        {
            this.DefaultSearchFilterDictionary = new LazyDictionary<string, string>();
            this.SavedFiltersDictionary = new LazyDictionary<string, SearchFilter>();
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type SavedUserFilter
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.SavedFiltersDictionary != null)
            {
                if (this.SavedFiltersDictionary is ILazyCollection<KeyValuePair<string, SearchFilter>> == false || ((ILazyCollection<KeyValuePair<string, SearchFilter>>)this.SavedFiltersDictionary).IsInitialized)
                {
                    JObject searchFilterDictionary = new JObject();
                    outputObject["SearchFilter"] = searchFilterDictionary;
                    foreach (KeyValuePair<string, SearchFilter> pair in this.SavedFiltersDictionary)
                    {
                        string searchFilterKey = pair.Key;
                        SearchFilter searchFilterValue = pair.Value;
                        if (searchFilterValue != null)
                        {
                            searchFilterDictionary[searchFilterKey] = searchFilterValue.SerializeJson(null);
                        }
                    }
                }
            }
            if (this.DefaultSearchFilterDictionary != null)
            {
                if (this.DefaultSearchFilterDictionary is ILazyCollection<KeyValuePair<string, string>> == false || ((ILazyCollection<KeyValuePair<string, string>>)this.DefaultSearchFilterDictionary).IsInitialized)
                {
                    JObject stringDictionary = new JObject();
                    outputObject["String"] = stringDictionary;
                    foreach (KeyValuePair<string, string> pair2 in this.DefaultSearchFilterDictionary)
                    {
                        string stringKey = pair2.Key;
                        string stringValue = pair2.Value;
                        if (stringValue != null)
                        {
                            stringDictionary[stringKey] = stringValue;
                        }
                    }
                }
            }
            return outputObject;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken searchFilterDictionary = ((JToken)inputObject["SearchFilter"]);
                if (searchFilterDictionary != null && searchFilterDictionary.Type != JTokenType.Null)
                {
                    foreach (JProperty property in searchFilterDictionary)
                    {
                        SearchFilter searchFilter = new SearchFilter();
                        searchFilter.DeserializeJson(property.Value);
                        this.SavedFiltersDictionary.Add(((string)property.Name), searchFilter);
                    }
                }
                JToken stringDictionary = ((JToken)inputObject["String"]);
                if (stringDictionary != null && stringDictionary.Type != JTokenType.Null)
                {
                    foreach (JProperty property2 in stringDictionary)
                    {
                        this.DefaultSearchFilterDictionary.Add(((string)property2.Name), ((string)property2.Value));
                    }
                }
            }
        }
    }
}
