// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class Schedule
    {
        private DateTimeOffset? _endDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? EndDate
        {
            get { return this._endDate; }
            set { this._endDate = value; }
        }
        
        private int? _scheduleDuration;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? ScheduleDuration
        {
            get { return this._scheduleDuration; }
            set { this._scheduleDuration = value; }
        }
        
        private DateTimeOffset? _startDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? StartDate
        {
            get { return this._startDate; }
            set { this._startDate = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Schedule class.
        /// </summary>
        public Schedule()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Schedule
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.EndDate != null)
            {
                outputObject["EndDate"] = this.EndDate.Value;
            }
            if (this.ScheduleDuration != null)
            {
                outputObject["ScheduleDuration"] = this.ScheduleDuration.Value;
            }
            if (this.StartDate != null)
            {
                outputObject["StartDate"] = this.StartDate.Value;
            }
            return outputObject;
        }
    }
}
