// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Microsoft.IT.GRM.ServiceClient.Models;
using Newtonsoft.Json.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class SearchFilter
    {
        private string _filterName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string FilterName
        {
            get { return this._filterName; }
            set { this._filterName = value; }
        }
        
        private SearchFilters _filters;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public SearchFilters Filters
        {
            get { return this._filters; }
            set { this._filters = value; }
        }
        
        private string _requestStatus;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RequestStatus
        {
            get { return this._requestStatus; }
            set { this._requestStatus = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SearchFilter class.
        /// </summary>
        public SearchFilter()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type SearchFilter
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.FilterName != null)
            {
                outputObject["FilterName"] = this.FilterName;
            }
            if (this.Filters != null)
            {
                outputObject["Filters"] = this.Filters.SerializeJson(null);
            }
            if (this.RequestStatus != null)
            {
                outputObject["RequestStatus"] = this.RequestStatus;
            }
            return outputObject;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken filterNameValue = inputObject["FilterName"];
                if (filterNameValue != null && filterNameValue.Type != JTokenType.Null)
                {
                    this.FilterName = ((string)filterNameValue);
                }
                JToken filtersValue = inputObject["Filters"];
                if (filtersValue != null && filtersValue.Type != JTokenType.Null)
                {
                    SearchFilters searchFilters = new SearchFilters();
                    searchFilters.DeserializeJson(filtersValue);
                    this.Filters = searchFilters;
                }
                JToken requestStatusValue = inputObject["RequestStatus"];
                if (requestStatusValue != null && requestStatusValue.Type != JTokenType.Null)
                {
                    this.RequestStatus = ((string)requestStatusValue);
                }
            }
        }
    }
}
