// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Microsoft.IT.GRM.ServiceClient.Models;
using Newtonsoft.Json.Linq;

namespace Microsoft.IT.GRM.ServiceClient.Models
{
    public partial class UserPreferenceSavedUserFilter
    {
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private SavedUserFilter _preference;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public SavedUserFilter Preference
        {
            get { return this._preference; }
            set { this._preference = value; }
        }
        
        private string _type;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Type
        {
            get { return this._type; }
            set { this._type = value; }
        }
        
        private string _userAlias;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string UserAlias
        {
            get { return this._userAlias; }
            set { this._userAlias = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the UserPreferenceSavedUserFilter
        /// class.
        /// </summary>
        public UserPreferenceSavedUserFilter()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type UserPreference[SavedUserFilter]
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id.Value;
            }
            if (this.Preference != null)
            {
                outputObject["Preference"] = this.Preference.SerializeJson(null);
            }
            if (this.Type != null)
            {
                outputObject["Type"] = this.Type;
            }
            if (this.UserAlias != null)
            {
                outputObject["UserAlias"] = this.UserAlias;
            }
            return outputObject;
        }
    }
}
